export const metadata = { title: 'Terms of Service · Zi Wei Chart', description: 'Zi Wei Chart terms of service and user agreement' };

export default function TermsPage() {
  return (
    <>
      <header style={{ position: 'sticky', top: 0, zIndex: 50, background: 'var(--bg-0)', borderBottom: '1px solid var(--bdr)', padding: '14px 24px', display: 'flex', alignItems: 'center', gap: '16px' }}>
        <a href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', fontSize: '13px', color: 'var(--tx-3)', textDecoration: 'none' }}>
          <span style={{ fontSize: '16px' }}>‹</span>
          <span>Back to home</span>
        </a>
        <div style={{ width: '1px', height: '20px', background: 'var(--bdr-med)' }} />
        <span style={{ fontSize: '12px', color: 'var(--ac)', letterSpacing: '0.2em' }}>Zi Wei Chart</span>
      </header>
      <main style={{ maxWidth: 800, margin: '0 auto', padding: '60px 24px 80px', color: 'var(--tx-1)', lineHeight: 1.8 }}>
        <h1 style={{ fontSize: 28, fontWeight: 600, marginBottom: 8 }}>Terms of Service</h1>
        <p style={{ fontSize: 12, color: 'var(--tx-3)', marginBottom: 32 }}>Last updated: April 2026</p>

      <h2 style={{ fontSize: 18, marginTop: 32, marginBottom: 12 }}>1. Service Overview</h2>
      <p>Zi Wei Chart (hereinafter "the Platform") provides chart generation and reading services based on Ni Haixia's <em>Tian Ji</em> Zi Wei Dou Shu system. All divination content on this Platform is for reference only and <strong>does not constitute medical, investment, legal, psychological counseling, or major life-decision advice</strong>.</p>

      <h2 style={{ fontSize: 18, marginTop: 32, marginBottom: 12 }}>2. User Conduct</h2>
      <p>By using this Platform you agree to:</p>
      <ul style={{ paddingLeft: 24 }}>
        <li>Use the Platform only for lawful, personal reference purposes</li>
        <li>Not distribute Platform content for commercial sale, reproduction, or public publication</li>
        <li>Not engage in any behavior that disrupts normal Platform operation</li>
        <li>Submit accurate birth information; the Platform is not responsible for reading inaccuracies caused by incorrect input</li>
      </ul>

      <h2 style={{ fontSize: 18, marginTop: 32, marginBottom: 12 }}>3. Intellectual Property & Prohibited Uses · Anti-Scraping & Anti-Training</h2>
      <p style={{ background: 'rgba(168,50,40,0.06)', border: '1px solid rgba(168,50,40,0.2)', padding: 16, borderRadius: 8 }}>
        <strong>All divination content, knowledge base (including all reading text for 14 major stars × 12 palaces × gender × Si Hua × Da Xian / Liu Nian), UI design, algorithm integration, and case library on this Platform are original works or lawfully compiled materials belonging to the Platform.</strong><br/><br/>
        The following actions are strictly prohibited; violators will be subject to civil and criminal liability:<br/>
        ① Scraping Platform content by any technical means including crawlers, automated scripts, or batch API calls;<br/>
        ② Using chart readings, text, or API response data generated by this Platform <strong>to train any machine learning model</strong> (including but not limited to large language models, divination generation models, or text generation models);<br/>
        ③ Reselling or publishing Platform-generated content on other websites, apps, or social media accounts;<br/>
        ④ Decompiling, copying, or modifying the Platform's frontend or backend code to offer equivalent services under a different name.<br/><br/>
        Platform output text contains fingerprint traceability watermarks; unauthorized copying or training using this output can be detected and traced. Upon discovery of any violation, the Platform reserves the right to claim <strong>CNY 1,000,000 per violation</strong> and to pursue litigation or cooperate with law enforcement authorities.
      </p>

      <h2 style={{ fontSize: 18, marginTop: 32, marginBottom: 12 }}>4. Disclaimer</h2>
      <p>Platform divination content is based on traditional Zi Wei Dou Shu and Ni Haixia system knowledge and <strong>does not guarantee 100% accuracy</strong>. Fate is influenced by the three dimensions of Heaven, Earth, and Human; Platform output is provided solely as a reference for self-understanding. Users should approach it rationally and should not over-rely on any single divination judgment.</p>
      <p>The Platform is not legally responsible for any consequences arising from use of its content (including but not limited to decision errors, psychological effects, or relationship changes).</p>

      <h2 style={{ fontSize: 18, marginTop: 32, marginBottom: 12 }}>5. Service Changes and Termination</h2>
      <p>The Platform reserves the right to adjust, suspend, or terminate part or all of its services at any time. Significant changes will be communicated to users via in-platform announcements or email.</p>

      <h2 style={{ fontSize: 18, marginTop: 32, marginBottom: 12 }}>6. Governing Law and Dispute Resolution</h2>
      <p>These terms are governed by the laws of the People's Republic of China. In the event of a dispute, the parties shall attempt friendly negotiation; if negotiation fails, the dispute shall be submitted to the competent People's Court in the jurisdiction where the Platform's operating entity is located.</p>

      <h2 style={{ fontSize: 18, marginTop: 32, marginBottom: 12 }}>7. Contact</h2>
      <p>For any questions, please contact us via the customer service WeChat or email published on the Platform.</p>

        <p style={{ marginTop: 48, fontSize: 12, color: 'var(--tx-3)' }}>
          <a href="/privacy" style={{ color: 'var(--ac)' }}>Privacy Policy</a> · <a href="/" style={{ color: 'var(--ac)' }}>Back to home</a>
        </p>
      </main>
    </>
  );
}
